# https://leetcode.com/problems/lexicographically-smallest-generated-string/

# Example 1:
# Input: str1 = "TFTF", str2 = "ab"
# Output: "ababa"
# Explanation:
# The table below represents the string "ababa"
# Index	T/F	Substring of length m
# 0	'T'	"ab"
# 1	'F'	"ba"
# 2	'T'	"ab"
# 3	'F'	"ba"
# The strings "ababa" and "ababb" can be generated by str1 and str2.
# Return "ababa" since it is the lexicographically smaller string.

class Solution:
    def generateString(self, str1: str, str2: str) -> str:
        
        # Lengths of input strings
        n, m = len(str1), len(str2)
        
        # Result string of length (n + m - 1)
        # Initialize with 'a' (default filler)
        s = ["a"] * (n + m - 1)
        
        # fixed[i] = True means s[i] is fixed and cannot be changed
        fixed = [False] * (n + m - 1)

        # -------- Step 1: Handle 'T' constraints --------
        # If str1[i] == 'T', then substring starting at i must match str2
        for i, ch in enumerate(str1):
            if ch == "T":
                
                # Place str2 into s starting from index i
                for j, c in enumerate(str2, i):
                    
                    # If already fixed and mismatch occurs → impossible
                    if fixed[j] and s[j] != c:
                        return ""
                    
                    # Assign character and mark as fixed
                    s[j], fixed[j] = c, True

        # -------- Step 2: Handle 'F' constraints --------
        # If str1[i] == 'F', substring at i must NOT match str2
        for i, ch in enumerate(str1):
            if ch == "F":
                
                # Check if current substring already differs from str2
                # If yes → nothing to do
                if any(str2[j - i] != s[j] for j in range(i, i + m)):
                    continue

                # Otherwise, we must break the match
                # Try to modify one non-fixed position
                for j in range(i + m - 1, i - 1, -1):
                    
                    # Only change if not fixed
                    if not fixed[j]:
                        s[j] = "b"   # change to something different
                        break
                else:
                    # No position available to break the match → impossible
                    return ""

        # Convert list to string and return
        return "".join(s)